---
language: python
python:
  - "2.7"
  - "3.6"
install:
  - gem install mdl
  - pip install tox
script:
  # First syntax, linting and pre-test stages
  - mdl -s relaxed egicli_README.md
  - tox -e pep8,bandit
